# https://symfony.com/doc/current/bundles/FOSUserBundle/configuration_reference.html
fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: App\Entity\User
    from_email:
        address: "%env(MAILER_FROM_ADDRESS)%"
        sender_name: "%env(MAILER_FROM_NAME)%"
    service:
        mailer: fos_user.mailer.twig_swift
