sonata_media:
    class:
        media: 'App\Entity\SonataMediaMedia'
        gallery: 'App\Entity\SonataMediaGallery'
        gallery_has_media: 'App\Entity\SonataMediaGalleryHasMedia'
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.youtube
                #- sonata.media.provider.dailymotion
                #- sonata.media.provider.vimeo

            formats:
                small: { width: 320 , quality: 240}
                big:   { width: 1280, quality: 95 }

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            directory: "%kernel.project_dir%/storage/upload/media"
            create: false

    providers:
        image:
            resizer: sonata.media.resizer.simple
            #resizer: sonata.media.resizer.square
