twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        - '@SonataMedia/Form/media_widgets.html.twig'
